server:
  port: 8080
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/web/page/*
    suffix: .html
  application:
    #应用名称
    name: school_system
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/school_system?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: a2462783924
#  main:
#    banner-mode: off #减少spring运行时控制台输出


mybatis-plus:
  configuration:
#    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
#    map-underscore-to-camel-case: true
    #开启mp日志（输出到控制台，可查看sql语句）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    banner: false #减少mybatis运行时控制台输出
#    db-config:
#      id-type: ASSIGN_ID
